---
- hosts: hosts
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - hosts
  handlers:
    - include : handlers/main.yml
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - switches
  handlers:
    - include : handlers/main.yml
