---
- hosts: host
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - hosts
  handlers:
    - include : handlers/main.yml
- hosts: leaf
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - switches
  handlers:
    - include : handlers/main.yml
